[phases.setup]
nixPkgs = ["sqlite", "nodejs-20_x"]

[phases.build]
cmds = [
  "touch database/database.sqlite",
  "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
  "npm ci",
  "npm run build"
]

[phases.start]
cmds = ["php artisan serve --host=0.0.0.0 --port=$PORT"]

[static]
  guest = "nginx"